# Generated by Django 5.2.2 on 2025-06-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='hire_data',
            new_name='hire_date',
        ),
    ]
